[dev]
description = "Dev mode"
run = """
mise exec -- bun --watch src/main.ts
"""

[lint]
description = "Check files with biome"
run = """
mise exec -- biome check --no-errors-on-unmatched
"""

[lint-fix]
description = "Fix files with biome"
run = """
mise exec -- biome check --no-errors-on-unmatched --write
"""

[typecheck]
description = "Run tsc"
run = """
mise exec -- tsc
"""

[test]
description = "Run tests"
run = """
mise exec -- bun test --coverage
"""

[test-staged]
description = "Run tests on staged files"
run = """
mise exec -- bun test --changed --bail --reporter=dots
"""

[test-ci]
description = "Run tests in ci mode"
run = """
mise exec -- bun test --bail --reporter=dots
"""

[sync-branch]
description = "Sync package manager deps"
run = """
mise install
mise prune -y
mise exec -- bun install --frozen-lockfile
"""
